version: '3.8'

services: 
  app:
    image: node:latest
    restart: unless-stopped
    volumes:
      - ../../:/workspaces:cached
    command: sleep infinity
    network_mode: service:db

  db:
    image: mariadb:latest
    restart: unless-stopped
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: Sj20032003
      MYSQL_DATABASE: pizza
      MYSQL_USER: root
      MYSQL_PASSWORD: Sj20032003
  
volumes:
  mariadb-data: